import type React from "react"
import type { Metadata, Viewport } from "next"
import Script from 'next/script'
import {NextIntlClientProvider} from 'next-intl';
import {getMessages} from 'next-intl/server';

import "../globals.css"
import { SITE_NAME, SITE_URL, TAGLINE, TWITTER_HANDLE } from "@/lib/site"

import { Playfair_Display, Crimson_Text, Geist as V0_Font_Geist, Geist_Mono as V0_Font_Geist_Mono, Source_Serif_4 as V0_Font_Source_Serif_4 } from 'next/font/google'

V0_Font_Geist({ subsets: ['latin'], weight: ["100","200","300","400","500","600","700","800","900"] })
V0_Font_Geist_Mono({ subsets: ['latin'], weight: ["100","200","300","400","500","600","700","800","900"] })
V0_Font_Source_Serif_4({ subsets: ['latin'], weight: ["200","300","400","500","600","700","800","900"] })

const playfair = Playfair_Display({
  subsets: ["latin"],
  variable: "--font-playfair",
  display: "swap",
})

const crimson = Crimson_Text({
  weight: ["400", "600", "700"],
  subsets: ["latin"],
  variable: "--font-crimson",
  display: "swap",
})

// Viewport configuration (separate from metadata in Next.js 15+)
export const viewport: Viewport = {
  width: 'device-width',
  initialScale: 1,
  maximumScale: 5,
  themeColor: [
    { media: '(prefers-color-scheme: light)', color: '#FAFAFA' },
    { media: '(prefers-color-scheme: dark)', color: '#000000' }
  ],
}

export const metadata: Metadata = {
  title: {
    default: `${SITE_NAME} - ${TAGLINE} | macOS Pomodoro Timer with YouTube Integration`,
    template: `%s | ${SITE_NAME}`
  },
  description: `Transform your productivity with ${SITE_NAME} - a minimalist Pomodoro timer featuring seamless YouTube playlist integration. Free macOS menubar app for focused work sessions with music. No login required.`,
  keywords: [
    "Pomodoro timer",
    "macOS productivity app",
    "YouTube music integration",
    "focus timer",
    "menubar app",
    "work timer",
    "productivity tool",
    "time management",
    "study timer",
    "concentration app",
    "pomodoro technique",
    "macOS menubar timer",
    "YouTube playlist timer",
    "free productivity app"
  ],
  authors: [{ name: SITE_NAME, url: SITE_URL }],
  creator: SITE_NAME,
  publisher: SITE_NAME,
  applicationName: SITE_NAME,
  generator: 'Next.js',
  metadataBase: new URL(SITE_URL),
  category: "Productivity",
  classification: "Productivity Software",

  // Robots and Indexing
  robots: {
    index: true,
    follow: true,
    googleBot: {
      index: true,
      follow: true,
      'max-video-preview': -1,
      'max-image-preview': 'large',
      'max-snippet': -1,
    },
  },

  // Canonical and Alternates
  alternates: {
    canonical: SITE_URL,
  },

  // Open Graph
  openGraph: {
    title: `${SITE_NAME} - ${TAGLINE} | macOS Pomodoro Timer`,
    description: "A minimalist Pomodoro timer with seamless YouTube playlist integration. Free macOS menubar app for productive work sessions.",
    type: "website",
    url: SITE_URL,
    locale: "en_US",
    siteName: SITE_NAME,
    // Images are automatically generated by opengraph-image.tsx
  },

  // Twitter Card
  twitter: {
    card: "summary_large_image",
    title: `${SITE_NAME} - ${TAGLINE} | macOS Pomodoro Timer`,
    description: "A minimalist Pomodoro timer with seamless YouTube playlist integration. Free for macOS.",
    // Images are automatically generated by opengraph-image.tsx
    creator: TWITTER_HANDLE,
    site: TWITTER_HANDLE,
  },

  // Icons and Manifest
  icons: {
    icon: [
      { url: '/icon.svg', type: 'image/svg+xml' },
      { url: '/favicon.ico', sizes: 'any' },
    ],
    apple: [
      { url: '/apple-icon.svg', type: 'image/svg+xml' },
      { url: '/apple-touch-icon.png', sizes: '180x180', type: 'image/png' },
    ],
    other: [
      {
        rel: 'mask-icon',
        url: '/safari-pinned-tab.svg',
      },
    ],
  },
  manifest: '/manifest.json',

  // Additional Metadata
  appleWebApp: {
    capable: true,
    statusBarStyle: 'default',
    title: SITE_NAME,
  },
  formatDetection: {
    telephone: false,
  },
}

export default async function RootLayout({
  children,
  params
}: Readonly<{
  children: React.ReactNode;
  params: Promise<{locale: string}>;
}>) {
  const {locale} = await params;
  const messages = await getMessages();

  return (
    <html lang={locale} className={`${playfair.variable} ${crimson.variable} antialiased`}>
      <head>
        <link
          rel="stylesheet"
          as="style"
          crossOrigin="anonymous"
          href="https://cdn.jsdelivr.net/gh/orioncactus/pretendard@v1.3.9/dist/web/variable/pretendardvariable.min.css"
        />

        {/* Google tag (gtag.js) */}
        <Script
          src="https://www.googletagmanager.com/gtag/js?id=G-HVE81J00X2"
          strategy="afterInteractive"
        />
        <Script id="google-analytics" strategy="afterInteractive">
          {`
            window.dataLayer = window.dataLayer || [];
            function gtag(){dataLayer.push(arguments);}
            gtag('js', new Date());
            gtag('config', 'G-HVE81J00X2');
          `}
        </Script>
      </head>
      <body>
        <NextIntlClientProvider messages={messages}>
          {children}
        </NextIntlClientProvider>
      </body>
    </html>
  )
}
